name: CI

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test "${{ matrix.scenario }}" scenario
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scenario:
          - import-meta

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Build
        run: pnpm run build:${{ matrix.scenario }}
